CUNY-CL/yoyodyne

- yoyodyne/datasets.py
Signed-off-by: bonham79 <travismbartley@gmail.com>
Changes dataset behavior for features that an exception is thrown if a feature is present in validation/testing/prediction that was unseen during training. This will force consistent feature labeling throughout.
Closes: https://github.com/CUNY-CL/abstractness/issues/130
> Datasets checks if feature was not seen during decoding.

- yoyodyne/predict.py
This rather simple PR takes the stance that the proper solution to https://github.com/CUNY-CL/yoyodyne/issues/26
is to simply not output the source or feature columns at all, which
simplifies the prediction loop considerably.
> Get out of the output formatting business

- README.md
- tests/model_test.py
- yoyodyne/models/__init__.py
- yoyodyne/models/lstm.py
- yoyodyne/train.py
This is now just part of the architecture specification, like it is underlyingly.
Closes #29.
> Removes --attention flag.

- yoyodyne/models/base.py
- yoyodyne/schedulers.py
- yoyodyne/train.py
- Adds schedulers.add_argparse_args
- Refactors _get_lr_scheduler
I added some other functions to schedulers, to support converting from yoyodyne argparse args, to the torch scheduler args. We may also want to consider exposing the interval and frequency of schedule updates to the CLI. In this way, the `total_decay_steps` for the decay scheduler could be total_decay_iters, and depend on whether you request that the scheduler potentially update every step or epoch.
Also -- when I run my local `black`, it seems to modify most files, so I reverted that and just used my flake8 config. Is there anywhere I can see the linting setup for this repo, and apply it to my local?
Addresses #28 28
> Adds LR decay scheduler.

- yoyodyne/schedulers.py
This immediately follows #31. It simplifies the `super` calls in the two schedulers and then tests both against some of our data.
> Cleanup to `super` calls in schedulers

- yoyodyne/models/base.py
- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/positional_encoding.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
- yoyodyne/train.py
* `--max_sequence_length` -> `--max_source_length`
* `--max_decode_length` -> `--max_target_length`
This addresses commentary in #40. However it leaves open other parts of the bug, namely that it does not add documentation nor raise exceptions when the max lengths are exceeded by training data.
> Rename length flags

- yoyodyne/models/base.py
- yoyodyne/schedulers.py
Also mildly reconfigures to make the printout more pleasant.
After (transformer with warmupinvsqrt):
<pre>Scheduler details:
[{&apos;scheduler&apos;: WarmupInverseSquareRootSchedule(Adam (
Parameter Group 0
amsgrad: False
betas: (0.9, 0.98)
capturable: False
differentiable: False
eps: 1e-08
foreach: None
fused: False
initial_lr: 0.001
lr: 0.0
maximize: False
weight_decay: 0
), 4000), &apos;interval&apos;: &apos;step&apos;, &apos;frequency&apos;: 1}]
</pre>
> Adds scheduler reprs

- README.md
- yoyodyne/train.py
The PTL trainer supports two kinds of auto-tuning as an alternative to actual training: one for batch size (which just tries to find the biggest value) and one for LR (which is a bit more sophisticated). Here, I have made the --auto_lr_find flag work.
If this flag is invoked, we run the tuner instead of the trainer's fit method, log the result, and then quit. Otherwise, training proceeds as normal.
I did not bother to enable the batch size one as it is substantially more work.
Only question is: do we want this?
> Adds automated LR tuning

- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
LSTM variants and pointer generator now works for >1 layers. There was a bug in the `init_hiddens` that used the number of encoder layers, not decoder. We also need to, for pointer generator, request only the last layer to use with the feature attentions.
However, the pointer generator now breaks when `encoder_layers != decoder_layers` because we follow the paper in initializing the decoder with the last encoder state. I *could* probably get the `n` last layers where `n` is `decoder_layers`, but this seems weird and also means that we still have the constraint that `encoder_layers >= decoder_layers`.
I think we either need to assert that `encoder_layers != decoder_layers`, or diverge from the paper and initialize the decoder like how we do the other LSTM models. I don't expect the latter …
> Fix lstm encoder layers

- yoyodyne/defaults.py
- yoyodyne/models/base.py
- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
- Updates validation step to only call model forawrd once.
- Adds teacher_forcing param to  forward and decode methods.
- Calls validation step with teacher_forcing=False.
- Updates  methods to decode until EOS AND at least length of target in teacher_forcing mode.
- Calls predict step with teacher_forcing=False.
Closes #70 
Adds `teacher_forcing`, which tells the model to decode using the gold history, rather than the predicted history. This is typically how encoder-decoder inflection models are trained, but during validation/prediction, we force teacher_forcing to be False.
I additionally implemented a check that makes validation more efficient: we supply the target tensor, but only use it for early stopping on decoding if the decoder has predicted an EOS token for every sequence in the …
> Fixes decoding twice in validation

- README.md
- yoyodyne/dataconfig.py
- yoyodyne/datasets.py
- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
Adds the non-existant (but still called -- oh the perils of writing software in interpreted languages!) `source_features_samples`, and makes fixes for when no target is passed through.
Also adds @kylebgorman's suggestion for passing `batch.target.padded` to `decode` when there is no target.
> Fixes predict no target

- yoyodyne/models/pointer_generator.py
This is for pointer-generator only.
> Standardizes use of "features" rather than "feature" when referring to the third column

- yoyodyne/train.py
This saves the checkpoint accuracies to 3 digits instead of 2, and stores 3-digit epoch counts.
> More precision in checkpoint names

- README.md
- yoyodyne/models/pointer_generator.py
That pointer-generators have the same number of encoder and decoder layers.
Closes #114.
> Improves documentation on the requirement

- README.md
- yoyodyne/data/datamodules.py
- yoyodyne/data/datasets.py
- yoyodyne/data/indexes.py
- yoyodyne/data/tsv.py
- yoyodyne/train.py
This makes it so that `yoyodyne-predict` works with `--features_col 0`. That is, if this is specified it doesn't bother to parse the features column at all, which saves you a little time.
It does this by delegating `has_features` and `has_target` to the parser rather than to the index, and fixes a sneaky bug on the last line of the datasets module.
> Better support for not parsing irrelevant fields

- examples/wandb_sweeps/train_wandb_sweep.py
As I understand it this is not the warning discussed in #78 but it's good to silence anyways.
The full error reads:
```
UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
```
@Adamits please let me konw if we want this.
> Silences warning about multiple WandB loggers

- yoyodyne/evaluators.py
- yoyodyne/models/base.py
- yoyodyne/models/transducer.py
Addresses #119
Marking this as a WIP as it's a little clunky, but wanted to get a PR up. Probably we should refactor the evaluator so the semantics of getting correct/total counts is clearer?
This fixes an issue where we report a macro accuracy over per-batch accuracies on the validation set, rather than a micro accuracy over all predictions.
> WIP: Fixes eval accuracy on epoch

- yoyodyne/models/base.py
- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transformer.py
- Changes loss functions to use `CrossEntropyLoss`.
- Overrides this for `PointerGenerator`, which needs to use `NLLLoss`
- Patches the main bug in #111
> Loss function updates

- yoyodyne/models/pointer_generator.py
I was not able to run the pointer-generator LSTM. It looks like the breaks have been here since #72.
- We now actually pass the encoded features through to the decode_step
- We correctly concatenate the feature attention if provided (previously we erroneously concatenated the source attention * 2)
- No longer adds the extra breaking dimension to the generation probability.
> Fixes several pointer-generator lstm bugs

- yoyodyne/data/datasets.py
We were adding the END token to a reference to the actual target sample every time we encoded it. When running some tests where I was evaluating a ton, I noticed that some eval samples would somehow become >128 (the max sequence length) causing an error. 
This ensures we append END to a copy of the target, so that between calls to __getitem__ we are no longer adding to the target token.
> Fixes END accumulation. makes encode_target append to a copy.

- yoyodyne/train.py
I also remove some seemingly pointless logging of model paths; can restore if there's a reason we need this.
Note that there exist alternatives: for instance we can log any checkpoint that's an improvement. From [the docs](https://lightning.ai/docs/pytorch/stable/extensions/generated/lightning.pytorch.loggers.WandbLogger.html):
```python
wandb_logger = WandbLogger(log_model="all")
checkpoint_callback = ModelCheckpoint(monitor="val_accuracy", mode="max")
trainer = Trainer(logger=wandb_logger, callbacks=[checkpoint_callback])
```
But I think this would still be excessive and I can't imagine why you'd want to log a checkpoint on W&B, tbh.
> W&B no longer "logs" (uploads) checkpoints.

- yoyodyne/train.py
Adds number of model parameters to W&B log. 
Note that PTL logs this to stdout by default, but it is convenient to have a column in W&B for this, so that we do not need to retrieve and parse all stdout logs for large analysis.
> Log model parameters to wandb

- yoyodyne/predict.py
Right now, if you 
1. Train a model with `pointer_generator_transformer` and features
2. Run prediction with the trained model
There is an "index out of range error":
```shell
Traceback (most recent call last):
File "/Users/USER/.pyenv/versions/3.10.13/bin/yoyodyne-predict", line 8, in <module>
sys.exit(main())
File "/Users/USER/.pyenv/versions/3.10.13/lib/python3.10/site-packages/yoyodyne/predict.py", line 158, in main
predict(trainer, model, datamodule, args.output)
File "/Users/USER/.pyenv/versions/3.10.13/lib/python3.10/site-packages/yoyodyne/predict.py", line 101, in predict
for batch in trainer.predict(model, loader):
File "/Users/USER/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 892, in predict
return …
```
> Fix prediction bug with pointer_generator_transformer

- yoyodyne/train.py
Hot fix for `hard_attention`
I was a silly billy and forgot to add `hard_attention` models to class of models that separates features in dataloading.
Fixes: https://github.com/CUNY-CL/yoyodyne/issues/194
> specifying 'seperate features' for hard_attention

- yoyodyne/evaluators.py
- yoyodyne/predict.py
- yoyodyne/util.py
In #184 I seem to have forgotten to test `predict.py`. It attempts to get a handle on the old `evaluator` in order to `finalize_predictions`, but now we have multiple evaluators and don't know which one to use.
Instead, this generalizes the notion of replacing everything after EOS in a tensor with a PAD and puts it in util.py. We can now use that for prediction in case the model predicts random chars after EOS. I also made minor clarifications to `evaluators.py`, where we sometimes `finalize_*` without replacing with PADs, as they are unnecessary if we aren't keeping a tensor as in the SER case.
I will need to test the evaluators beforemerging, but was hoping to get eyes on this for design or naming issues.
> Pad tensor after eos

- README.md
- examples/wandb_sweeps/train_wandb_sweep.py
- yoyodyne/defaults.py
- yoyodyne/sizing.py
- yoyodyne/train.py
In this follow-up to #194, I make it so that the batch size finder has two modes:
* `opt`imal mode is the same as before: it uses the gradient accumulation trick if necessary
* `max` mode just finds the max batch size and uses it, ignoring `--batch_size`
I theorize the latter would be really useful for when you have reason to believe the model does well with large batches (this might be all models?) and rather than tuning it, want to tune the other hyperparameters instead.
I am testing this with a fancy Bayesian sweep [here](https://wandb.ai/hyperparam-sensitivity/pol-max_batch-hard_monotonic_lstm?nw=nwuserkylebgorman) (the link may not be accessible to just anyone).
> Autosizing modes

- examples/wandb_sweeps/README.md
- examples/wandb_sweeps/best_hyperparameters.py
This script usees the W&B API to find the best run and then retrieve its hyperparameters. Some hacks are used to suppress redundant hyperparameters (or things that are not really hyperparameters) and to print them out as flags so that this could be used like:
yoyodyne-train ... $(./best_hyperparameters ...)
> Adds a script to retrieve hyperparameters

- yoyodyne/train.py
This one-line change logs that early stopping has kicked in. Without it there's no logging information about early stopping at all. There are other places we could in theory increase verbosity and I may issue PRs for those so we can see if we like them. 
Here is an example of what is logged. It's a bit verbose as you might expect:
```
Epoch 38: 100%|██████████| 3/3 [00:01<00:00,  2.44it/s, loss=2.71, v_num=pzub, val_accuracy=0.000, val_loss=3.020]Metric val_loss improved by 0.008 >= min_delta = 0.0. New best score: 3.021
Epoch 44: 100%|█████████| 3/3 [00:01<00:00,  2.54it/s, loss=2.51, v_num=pzub, val_accuracy=0.0084, val_loss=3.000]Metric val_loss improved by 0.022 >= min_delta = 0.0. New best score: 2.999
Epoch 45: 100%|█████████| 3/3 [00:01<00:00,  2.66it/s, loss=2.48, v_num=pzub, …
```
> Enables verbosity for early stopping/patience

- .circleci/config.yml
- README.md
- pyproject.toml
Enables support for Python > 3.10.
At some earlier point we were stuck on PyTorch <2, and there was no support for Python 3.10 or later. #173 freed us from this restriction, but left in the restriction to PyTorch-Lightning <2. However, we were pinned on Python <= 3.10 by PyTorch, not PyTorch-Lightning, so we can now add support for additional Pythons.
Python 3.12 is the actively developed branch; Python 3.8-3.11 are are on long-term (i.e., security-fix) support; Python 3.8 is just about to go out of date and Python 3.13 is approaching prerelease: https://devguide.python.org/versions/. So this adds support for all supported Python versions (except 3.8, which was already old when we started this project and which we never supported in the first place).
I have updated the patch-level since …
> Adds support for additional Python versions

- .circleci/config.yml
- README.md
- pyproject.toml
- yoyodyne/models/base.py
- yoyodyne/models/embeddings.py
- yoyodyne/models/lstm.py
- yoyodyne/models/modules/transformer.py
- yoyodyne/models/transformer.py
- yoyodyne/train.py
These were previously stored as static methods in the base model. But they are also needed at the module level, so we separate them. This should fix the break in the feature invariant transformer reported in #215. (Closes #215.)
> Moves embedding initialization to its own module

- README.md
- yoyodyne/train.py
The logic in `train.py` was to use a separate features encoder module if:
- features are present in the datamodule
- the model requires features to be separate from source (e.g., pointer-generators)
- and a separate features encoder module is requested.
This is incorrect; the logic should read:
- features are present in the datamodule, and
- a separate features encoder module is requested, or
- the model requires features to be separate from source.
In the case where the model requires it but a specific features encoder module is not specified, we use the same module as the source encoder; e.g., a pointer-generator LSTM will have an LSTM source encoder and an LSTM features encoder.
The README was also out of date: the flags are `--source_encoder_arch` and `--features_encoder_arch` (was …
> Fixes bug with optional features encoder

- yoyodyne/data/indexes.py
Current logic is such that source and target vocabularies (which are stored solely for logging and debugging purposes) are unioned together if `--tied_embeddings`. However, the purpose of these logging statements has nothing to do with embedding tying, so we modify them so that they are not combined except when building the actual vocabulary. We also remove the special symbols from the logging since they serve no purpose there.
Before (example with mostly-disjoint vocabulary...):
```
Source vocabulary: '<UNK>', '<P>', '<S>', '<E>', '1', '2', '5', '8', '9', '@', 'E', 'G', 'N', 'O', 'R', 'S', 'Z', 'a', 'b', 'd', 'e', 'f', 'g', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '§', '°', 'ø', 'ŋ', 'œ', 'œ̃', 'ɑ', 'ɑ̃', 'ɔ', 'ɔ̃', 'ə', 'ɛ', 'ɛː', 'ɛ̃', 'ɡ', …
```
> Separates vocabularies for logging

- yoyodyne/evaluators.py
- yoyodyne/models/__init__.py
- yoyodyne/models/lstm.py
- yoyodyne/sizing.py
- yoyodyne/train.py
* If something has a null default, don't list a default at all ("not enabled" isn't always precise enough).
* For a boolean flag (e.g., --foo/--no_foo) defaulting to true, give its default as "enabled".
* For a boolean flag defaulting to false, give its default as "not enabled".
* Mention that transducer architectures go wtih tied embeddings.
* Mention that patience_metric goes with patience.
> Cleanup of some flag help strings

- yoyodyne/models/modules/transformer.py
The feature invariant decoder reserves half of its capacity for features. This requires that its size be divisible by 2. I raise an explicit error in the unlikely case this is hit, and remove the FIXME. I am also using the more idiomatic // 2 rather than int(_ / 2).
> Cleans up documentation on the separate feature transformer decoder

- examples/wandb_sweeps/train_wandb_sweep.py
- yoyodyne/train.py
As reported in #227, memory is not freed after an OOM during the sweep, meaning that, usually, all subsequent sweeps also fail. We solve this by:
1. Cleaning up the `train.train` API with a more friendly endpoint. This has the desirable effect that there is no longer any need to keep `train_wandb_sweep.py` "up to date" with trainer interface: it just takes `args` and handles the rest.
2. Wrapping the call to `train.train` in a `try`/`except` with a `finally:` block that clears the CUDA cache.
Closes #227.
Sample test:
```
$ cat config/bad_config.yaml
method: random
metric:
name: val_accuracy
goal: maximize
parameters:
arch:
value: attentive_lstm
encoder_layers:
values: [1, 2]
embedding_size:
distribution: q_uniform
q: 16
min: 16
max: 512
hidden_size:
distribution: q_uniform
q: 64
min: 64 …
```
> Clears the cache after an OOM during sweeps

- yoyodyne/models/modules/transformer.py
We can just silence the warning by agreeing not to use the nested tensors backend.
Closes #214. Mutually exclusive with #224.
> Disables the use of nested tensors

- yoyodyne/__init__.py
- yoyodyne/data/collators.py
- yoyodyne/data/datamodules.py
- yoyodyne/data/indexes.py
- yoyodyne/data/tsv.py
- yoyodyne/evaluators.py
- yoyodyne/models/__init__.py
- yoyodyne/models/base.py
- yoyodyne/models/modules/__init__.py
- yoyodyne/schedulers.py
This makes it so that we use a consistent style for factories:
* `_foo_fac` defined out of line
* `_foo_fac.keys()` used to define the `--foo` `choices=` field in the argparser
* raises `NotImplementedError("[Thing] not found: {foo}")`
> Consistency fix for factory lookups

- examples/wandb_sweeps/best_hyperparameters.py
- examples/wandb_sweeps/train_wandb_sweep.py
- pyproject.toml
- requirements.txt
- yoyodyne/data/datamodules.py
- yoyodyne/models/__init__.py
- yoyodyne/models/base.py
- yoyodyne/models/expert.py
- yoyodyne/models/modules/base.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/predict.py
- yoyodyne/schedulers.py
- yoyodyne/sizing.py
- yoyodyne/train.py
- yoyodyne/util.py
This is no-op basically; we just have to change some of the imports and the requirements.
Closes #238.
> Moves from `pytorch-lighting` to `lightning` package.

- yoyodyne/models/base.py
- yoyodyne/train.py
We have special logic inside the trainer which logs, to W&B (and only if enabled), the number of parameters. This makes two changes:
1. the actual logic into summing the parameters across the elements is moved into the base model.
2. the name of the logged quantity is given a more informative name.
Nothing else changed.
> Moves parameter counting into base model

- yoyodyne/models/hard_attention.py
The bug reports a failure to pass the embeddings to the module.
Closes #258.
> Closes #258.

- yoyodyne/data/indexes.py
There is just one location where this is useful.
For context, see [PEP 563](https://peps.python.org/pep-0563/). 
Note that this is backwards compatible all the way back to Python 3.7 (which we don't even support) and thus harmless.
> Use future annotations

- README.md
- yoyodyne/data/datamodules.py
- yoyodyne/data/indexes.py
- yoyodyne/predict.py
- yoyodyne/train.py
This adds an extra flag to every command and for what? If you want to keep model directories separate for different experiments in a way that goes beyond already done with the automated versioning, you can just append a subdirectory name to `--model_dir`, e.g., using `--model_dir models/foo` instead of `--model_dir models --experiment foo`.
The README is updated to reflect.
> Removes separate "experiment" subdirectory

- pyproject.toml
- yoyodyne/data/datamodules.py
- yoyodyne/data/indexes.py
- yoyodyne/models/expert.py
- yoyodyne/predict.py
- yoyodyne/train.py
- yoyodyne/util.py
* Because the index is now all compromised of what `pickle` considers to be POD types (previously it consisted of separate `Vocabulary` objects), we can just load it directly without `setattr` now.
* To support this (and a few other things) we add a utility called `mkpath` which creates all the subdirectories needed and use this in all the cases where we are writing to a user-specified file.
* For simplicity we let the datamodule write the index. Less logic in `train` or `predict`: easier migration to LightningCLI.
* Gets rid of some unused stuff in the index.
> Cleanup to index writing

- README.md
- pyproject.toml
- yoyodyne/data/__init__.py
- yoyodyne/data/collators.py
- yoyodyne/data/datamodules.py
- yoyodyne/data/datasets.py
- yoyodyne/data/indexes.py
- yoyodyne/data/mappers.py
- yoyodyne/data/tsv.py
- yoyodyne/models/__init__.py
- yoyodyne/models/expert.py
- yoyodyne/predict.py
- yoyodyne/train.py
Borrowing a design element I used in UDTube, I decompose the dataset object into two pieces:
* a `Mapper` interface which knows how to map between lists of strings and tensors (to decode and encode)
* `DataSet`, as before.
There was no particular reason for the mapper functions to live inside the dataset. This separates the two pieces and uses the mapper object for prediction.
Closes #137. That issue says that the encoding/decoding should be moved to the index, but this actually makes those two even more modular.
(I also imported fix #272 and resolved some merge stuff from #268 etc.)
> Moves to mapper interface

- yoyodyne/models/modules/transformer.py
This reverses a line in #264.
I think this only affects CPU or MPS; error without reads:
```
File ".../site-packages/torch/nn/functional.py", line 2551, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got CPUBoolType instead (while checking arguments for embedding)
```
> One necessary `long` conversion

- yoyodyne/evaluators.py
- yoyodyne/models/base.py
- yoyodyne/models/hard_attention.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transformer.py
Reviewing the code I noticed quite a few places where we use `torch.max`, which returns a max/argmax tuple, but then we throw away the max using either `_, argmax = torch.max(...)` or `argmax = torch.max(...)[1]`. In each case, found using `grep`, I just use `torch.argmax` instead. Whether or not this is more performant it expresses the intention more clearly.
> Replaces notional argmaxes with `torch.argmax`

- yoyodyne/data/mappers.py
- yoyodyne/models/base.py
- yoyodyne/models/rnn.py
- yoyodyne/predict.py
* We remove the restriction of beam search to batches of size 1. If in the future beam search is generalized, prediction will "just work".
* We remove the need to call the ugly pad_after_end helper function during prediction using much simpler logic in the mapper module. This function is still needed at present for compatible evaluation, but subsequent PRs will address that.
* We remove a bunch of transpositions in `RnnModel` by keeping B as the leading dimension. This is good style anyways because B-first is assumed by just about all the library code.
> Generalizes predictions for batches > 1

- yoyodyne/models/rnn.py
The length bounds for greedy decoding are as follows:
* If a target is provided, we need loss and maybe also are doing teacher forcing, and therefore do as many decoding steps as the longest sequence in the target tensor.
* If no target is provided, then `max_target_length` acts as an upper bound. However, we can halt earlier if all sequences have decoded at least one END.
This disjunction is currently not well encoded: we generate a vector
`finished` (tracking the presence of END in the sequences), and repeatedly update and test it, even in the case where a target is present. This PR fixes that: the vector is only generated, updated, and tested if no target is present.
We also update the method docs to reflect this and to draw the contrast with beam decoding.
This has no effects on the …
> Simplifies greedy decoding in the RNN

- yoyodyne/models/base.py
- yoyodyne/models/modules/base.py
- yoyodyne/models/modules/rnn.py
- yoyodyne/models/modules/transformer.py
Both base model and base module have a dropout layer, but the base model's dropout is unused. I remove it. We still pass the dropout probability to the modules, of course.
The base module dropout is defined as an out-of-place operation, but there are several places where we do:
```python
self.dropout_layer = nn.Dropout(..., inplace=False)
...
output = ...
output = self.dropout_layer(output)
```
Knowing what I know about Python internals this is pretty expensive:
* The RHS of the final expression to be computed before the assignment, so we temporarily have two copies of `output` (one dropped out, one not) in memory.
* This also "thrashes" the GC a bit: it has to deallocate the first one (its reference count will become zero after the reassignment) to clean up the mess.
In contrast: …
> Audits dropout layers

- README.md
- yoyodyne/data/datamodules.py
- yoyodyne/evaluators.py
- yoyodyne/models/__init__.py
- yoyodyne/models/base.py
- yoyodyne/models/expert.py
- yoyodyne/models/hard_attention.py
- yoyodyne/models/modules/__init__.py
- yoyodyne/models/modules/attention.py
- yoyodyne/models/modules/base.py
- yoyodyne/models/modules/hard_attention.py
- yoyodyne/models/modules/linear.py
- yoyodyne/models/modules/rnn.py
- yoyodyne/models/modules/transformer.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/rnn.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
- yoyodyne/predict.py
- yoyodyne/train.py
PEP 3119 introduced decorators for declaring abstract methods. This PR uses them throughout the model, module, and evaluator hierarchies.
This is definitely superior to what we did before #254, which was to just declare but not implement these. Since that's the same as having a no-op null-return function, an unimplemented method in a concrete class just returns `None`. Usually, this will trigger failures somewhere downstream at run-time but the errors are completely uninformative and hard to trace down.
In #254, which added GRU support, I changed these to raise `NotImplementedError`. This means we get a fatal error (assuming we've wrapped things in an overly-general `try`/`except`) when the methods are called. 
With PEP 3119, we make `BaseModel`, `BaseModule`, etc. inherit (directly) from …
> Enforce abstraction with PEP 3119

- yoyodyne/models/base.py
- yoyodyne/models/modules/base.py
- yoyodyne/models/modules/rnn.py
- yoyodyne/models/modules/transformer.py
This reverts an earlier change (#293) which added in-place dropout. On my PC (Windows 11, WSL, older Nvidia GPU) in-place dropout throws the inscrutable message:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 1, 512]], which is output 0 of CudnnRnnBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
Tracing down this mysterious tensor of shape 128 x 1 x 512 I found that it was the tensor input to dropout.
Since I didn't see this on my laptop I suspect it is quite literally platform-dependent. 
Note however that I now instead avoid the expensive …
> Reverts use of in-place dropout

- yoyodyne/schedulers.py
When using the warmup inverse square root scheduler, if one specifies no warmup, you will hit the following error:
```
return self.decay_factor * step**-0.5
~~~~^^~~~~
ZeroDivisionError: 0.0 cannot be raised to a negative power
```
This can simply be avoided by treating step as 1-based. We already do this in the warmup clause, so we now do this in the warmed-up clause too. I also slightly improve the comments since this is an important point.
> Avoids 0-to-a-negative exponent error

- yoyodyne/models/pointer_generator.py
The implementation of pointer-generator RNNs contains disjunctions in the `forward` method which determine whether to use the encoder's hidden state as the input to the decoder, or the learned `h0` (and `c0` for LSTMs). We remove the disjucntion and just use the learned ones all the time (cf. #303). 57 lines of code are removed; my tests find no accuracy or latency regressions. 
Closes #304.
This will also support my effort to have less GRU/LSTM-specific code at the `model` level; more coming soon.
> Always uses learned initialization for pointer-generator

- yoyodyne/models/transducer.py
This causes transducers to use the learned decoder hidden state rather than the encoder hidden state. This is parallel to #310 but for transducers rather than pointer-generators.
I believe because of the way this was initially set up, it is no-op in many cases and just involves deleting unreachable code.
To confirm, I confirmed that performance on two languages and with GRUs and LSTMs was exactly the same before and after.
> Always use learned decoder hidden state in transducers

- yoyodyne/models/hard_attention.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/rnn.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
Transformers and RNNs do not yet support separate features encoders. Making them do so is probably straightforward, but in the meantime we make them raise an error. (This happens during the `forward` phase, which is late, but this is a temporary measure.)
Addresses but does not close #313.
> Raises error with unsupported features encoders

- yoyodyne/models/base.py
- yoyodyne/models/hard_attention.py
This simplifies how the greedy prediction is returned in the hard attention decoding loop.
> Slight simplification in hard attention loop

- README.md
- pyproject.toml
- yoyodyne/models/hard_attention.py
- yoyodyne/models/modules/__init__.py
- yoyodyne/models/modules/embedding.py
- yoyodyne/models/rnn.py
This PR adds support for separate encoders in vanilla RNNs; it addresses #313 (but doesn't touch transformers so it does not close it). We adopt the merging approach from the hard attention models, which works with both "linear" and RNN features encoders. Suppose that the source encoder generates $B \times L \times E$ and the features encoder generates $B \times L' \times E'$. To create the final encoding, we first average features encodings across all positions producing a tensor of size $B \times 1 \times E'$. We then expand this tensor to $B \times L \times E'$ by broadcasting it across all positions in the source tensor. We then concatenate along the encoding dimension, producing a new tensor of size $B \times L \times (E + E')$.  The effect can be likened to spreading the features …
> Supports separate encoders with vanilla RNNs

- examples/wandb_sweeps/README.md
- examples/wandb_sweeps/get_hyperparameters.py
The best_hyperparameters.py script is limited because it doesn't understand max/min logic. That is, it **cannot** report which run achieved the highest validation accuracy, only which had the highest final validation accuracy. However, you can retrieve this information from the W&B website.
Therefore we modify this script to take a run as argument and return its hyperparameters. Sample use:
```
./get_hyperparameters.py cuny-cl/SIGMORPHON-2020-pointer_generator_rnn-kor_rom/qhl0rqhv
```
This returns the hyperparameters for that run, which I previously determined to be the best using W&B's run spreadsheet.
> Replaces best_hyperparameters

- pyproject.toml
- tests/testdata/configs/real_trainer.yaml
- tests/testdata/configs/toy_trainer.yaml
- yoyodyne/cli/main.py
- yoyodyne/cli/sweep.py
In a previous revision I attempted to set things up so a CSV logger was always automatically configured. This does not play nice with W&B sweeps though: for reasons I don't fully understand, it would:
* rename every run in a sweep to "lightning_logs" after initialization
* attempt and fail to write `config.yaml` to the same location, causing a failure on later runs.
Some minor drive-bys are done on sample config files as well and logging is enabled for the sweep engine.
> Fixes auto-config of loggers
