- yoyodyne/models/base.py
> Only logs scheduler if one is being used

- yoyodyne/__init__.py
- yoyodyne/predict.py
> Removes all remaining uninformative warnings

- README.md
> Updates Readme with Model checkpointing section

- yoyodyne/train.py
> Removes train_set as a model arg

- yoyodyne/indexes.py
- yoyodyne/train.py
> Hotfix to write index before training loop

- requirements.txt
- yoyodyne/models/base.py
Okay, let's see if this works.
> Upgrading `black` to get beyond CircleCI issue

- yoyodyne/predict.py
> Fixes mkdir issue in predict

- yoyodyne/batches.py
- yoyodyne/collators.py
- yoyodyne/datasets.py
- yoyodyne/predict.py
- yoyodyne/train.py
Addresses #40 
Adds the length comparison and message as a callback, which the padded tensor calls.
I also snuck in a little fix to `datasets.Item`.
> Maximum padded length errors

- yoyodyne/collators.py
- yoyodyne/dataconfig.py
- yoyodyne/defaults.py
- yoyodyne/models/base.py
- yoyodyne/models/expert.py
- yoyodyne/models/lstm.py
- yoyodyne/models/positional_encoding.py
- yoyodyne/models/transformer.py
- yoyodyne/train.py
Adds a module for default constants and uses them.
This closes #52.
> Defaults module

- yoyodyne/models/pointer_generator.py
- Changes var name to ptr probs
- instantiates ptr_probs to use dtype of source_attention_weights
> Fixes 16bit pointer-generator

- yoyodyne/predict.py
- removes deprecated attention arg
> Fixes predict.get_model

- yoyodyne/models/base.py
This printout doesn't seem to serve much purpose since one can read the same information off of the `Arguments` printout, and I'm not sure what most of the information printed here means anyways...
> Removes optimizer details" printout

- tests/collator_test.py
- yoyodyne/datasets.py
- yoyodyne/indexes.py
We currently have two different index classes plus a base class, differing in only whether or not they include a features map. This PR combines the two and thus eliminates quite a few lines of code using a just a tiny bit of nullability and associated checking.
> Combines index classes

- yoyodyne/models/positional_encoding.py
* Shorter form of superclass construction.
* Use in-place multiplication.
> Cleanup to positional encoding

- yoyodyne/models/generation_probability.py
- yoyodyne/models/lstm.py
- yoyodyne/models/pointer_generator.py
Also uses some in-place operations.
> Cleans up variable naming to PEP-8 standard

- yoyodyne/evaluators.py
Also a drive-by: missing f-prefixes in the error message.
> Fixes variable naming in evaluators

- examples/wandb_sweeps/train_wandb_sweep_agent.py
Now each CLI override is logged.
> More clearly logs conflicts

- yoyodyne/models/base.py
- yoyodyne/models/modules/__init__.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/train.py
We are somewhat inconsistent but I think this is the best parallel and follows what's done at the CLI level.
> Calls the features stuff "features", with a plural.

- yoyodyne/models/__init__.py
- yoyodyne/models/base.py
- yoyodyne/models/lstm.py
- yoyodyne/models/modules/__init__.py
- yoyodyne/models/modules/linear.py
- yoyodyne/models/modules/lstm.py
- yoyodyne/models/modules/transformer.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
Instead of logging at lookup, logs at the end of class construction. Example:
```
Model: pointer-generator
Source encoder: LSTM
Features encoder: linear
Decoder: attentive LSTM
```
Closes #104.
> Improves model logging

- yoyodyne/train.py
> Fixes train args.

- yoyodyne/train.py
Found one more little comment fix left over from #110 
Hopefully this is all?
> Updates old arg documentation for get_model_from_argparse_args

- yoyodyne/data/__init__.py
- yoyodyne/data/datamodules.py
- yoyodyne/predict.py
- yoyodyne/train.py
This can be restored at a later date when it is made to do something.
Closes #124.
> Removes tied vocabulary flag

- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
Small update to documentation. It looks like these architectures now handle features conditionally in their implementation.
> Fixes pointer_generator and transducer documentation wrt features

- README.md
> Adds documentation for multi-batch accumulation.

- pyproject.toml
New release fixing transformer bug.
> Bumps version

- yoyodyne/schedulers.py
> Fixes min_learning_rate bug

- examples/wandb_sweeps/train_wandb_sweep.py
Added clean up at the end of the training function to free up the resources as suggested [here ](https://github.com/wandb/wandb/issues/1247#issuecomment-1457737657)
> Possible cure for W&B memory leak

- pyproject.toml
- requirements.txt
> Updates Maxwell dependency to >= 0.2.3

- yoyodyne/evaluators.py
> Cuda numpy ser hotfix

- yoyodyne/evaluators.py
- yoyodyne/models/transducer.py
I guess I had forgotten to test the Transducer with this change---it break since it has already "finalized" the prediction tensors. This fixes that by allowing for finalized predictions.
> Updates new evaluators code to work with Transducer.

- pyproject.toml
- yoyodyne/models/base.py
This release incorporates:
* Hard monotonic attention
* Hotfix #197 (since that's an actual breakage in my tests)
I conducted relatively extensive local testing across architectures with and without features.
> Release v0.2.11

- yoyodyne/models/modules/lstm.py
> Fixes typing issues raised in #199

- examples/wandb_sweeps/train_wandb_sweep.py
- yoyodyne/sizing.py
- yoyodyne/train.py
Closes #208. See #208 for context.
> Implements #208

- yoyodyne/models/transducer.py
Currently, the transducer predictions are right-padded with EOS (and indeed it seems to learn to make predictions in this way). Our gold tensors are right padded with PADs, and other models have their predictions 'finalized' so that everything after the first EOS symbol is replaced with a PAD.
This ensures that the transducer is finalized in the same way, which fixes some accuracty errors I was seeing. 
Note that in my tests for english-medium sigmorphon-2017 data, the transducer still seems to learn to copy the lemma and not correctly inflect, so there still may be further issues that I have been investigating in #207 
EDIT: closes #207
> Unifies tensor finalizing during eval

- yoyodyne/data/tsv.py
- yoyodyne/defaults.py
- yoyodyne/predict.py
> Adds explicit encoding arg for text files

- yoyodyne/models/modules/transformer.py
I include the citation for pre-layer normalization.
I also move docs from __init__ to the class-level docs. Because of symbol mangling it is really hard (reqiures metaprogramming) for the user to programmatically access the docs for an __init__ method. Thus the convention is to place them at the class level, a convention most tooling understands. This should be done more widely but I'll limit myself to this module for now.
> Adds docs to the transformer module

- yoyodyne/data/__init__.py
- yoyodyne/data/batches.py
- yoyodyne/data/datasets.py
- yoyodyne/metrics.py
- yoyodyne/models/base.py
- yoyodyne/models/expert.py
- yoyodyne/models/hard_attention.py
- yoyodyne/models/lstm.py
- yoyodyne/models/modules/attention.py
- yoyodyne/models/modules/lstm.py
- yoyodyne/models/pointer_generator.py
- yoyodyne/models/transducer.py
- yoyodyne/models/transformer.py
- yoyodyne/schedulers.py
This is what Python tooling (and LightingCLI) expect. Cf. #239.
> Moves initializer args to class-level docstrings.

- yoyodyne/data/datamodules.py
- yoyodyne/data/datasets.py
- yoyodyne/data/tsv.py
* I declare `SampleType` and use it to express the idea that a sample is a complex tuple-like object. (Previously I said, incorrectly, that it was a list of lists of string.): changes to `datasets.py` and `tsv.py`.
* I fix two minor typing bugs in `datamodules.py`.
> Some minor typing fixes in the data submodule.

- examples/wandb_sweeps/README.md
- examples/wandb_sweeps/sweep.py
Oops, accidentally broke something fixing a typo in a flag doc.
> Black fix and reflow

- yoyodyne/data/batches.py
> Generates mask as needed.

- yoyodyne/data/batches.py
> Fixes bug in pad mask generation

- yoyodyne/predict.py
> Expands list of separate features models

- yoyodyne.bib
- yoyodyne/models/transducer.py
> Adds some missing bibliography.

- yoyodyne/models/rnn.py
The beam search implementation tracks, in addition to the (incomplete) log-likelihood of each candidate, a list of likelihoods for each character. However, this quantity is never used for anything and removing it does not change operation except using slightly less memory.
> Removes unused char-likelihoods in beam search

- yoyodyne/models/hard_attention.py
This eliminates a repeated ternary in the definition of the hard attention classes simply by making it a property of the ABC.
> Adds helper for sizing the decoder input size

- yoyodyne/models/modules/hard_attention.py
* Adds a helper for computing the emission probabilities.
* Gives consistent names to this and the transition probability helper.
* Uses positive rather than negative indices (which IMO are easier to debug with).
> Helper for emission probability
